export type Lang = "en" | "es";

export const homeContent: Record<Lang, Record<string, string>> = {
  en: {
    "hero-eyebrow": "Business Consulting for Trade & Surface Shops",
    "hero-h1": "You cut the stone.<br/><em>I help you grow<br/>the business.</em>",
    "hero-sub":
      "Strategic consulting and digital marketing for fabricators, countertop shops, and surface retailers — from someone who has spent 10 years in your industry.",
    "hero-btn1": "Take the Free Growth Audit →",
    "hero-btn2": "Book a Free Strategy Call",
    stat1: "Years in the Trade",
    stat2: "Languages Served",
    stat3: "Free Audit",
    stat4: "Free Strategy Call",
    "prob-eyebrow": "Sound Familiar?",
    "prob-h2": "Most shops are great at the craft.<br/>The business side is another story.",
    p1h: "Customers buying elsewhere",
    p1p: "Your countertop clients are buying flooring, cabinets, and vanities from a competitor — and you're not even in the conversation.",
    p2h: "Invisible online",
    p2p: "Your work is beautiful but your website is outdated, you don't show up on Google, and your social media is inconsistent at best.",
    p3h: "No referral system",
    p3p: "You finish a great install and move on. No follow-up, no referral ask, no email sequence. Revenue that should be automatic isn't.",
    p4h: "Competing on price",
    p4p: "Without premium positioning, you're stuck fighting for jobs on price alone — even though your work deserves more.",
    "svc-eyebrow": "What I Do",
    "svc-h2": "Four areas where I move the needle",
    "svc-lead": "I work across strategy and execution — so you don't just get ideas, you get things done.",
    s1h: "Business Strategy",
    s1p: "Identify what you're leaving on the table, prioritize the highest-impact moves, and build a 90-day growth plan you can actually execute.",
    s1t1: "Growth Audit",
    s1t2: "Revenue Gaps",
    s1t3: "Product Mix",
    s2h: "Digital Marketing",
    s2p: "Google and Meta ads that bring in real leads, SEO that gets you found locally, and a website that converts visitors into calls.",
    s3h: "Marketing Assets",
    s3p: "Brochures, price lists, email campaigns, showroom materials — professional collateral that makes you look like the premium option.",
    s3t1: "Brochures",
    s3t2: "Email Campaigns",
    s3t3: "Showroom",
    s4h: "Sales Systems",
    s4p: "Referral programs, follow-up sequences, and builder/designer relationship strategies that turn your installs into a pipeline.",
    s4t1: "Referrals",
    s4t2: "Follow-Up",
    s4t3: "Builder Outreach",
    "who-eyebrow": "Who I Help",
    "who-h2": "Built for the trades — English & Spanish",
    "who-lead":
      "I serve shop owners across Utah and nationwide. Most of my clients are Spanish-speaking — and everything I offer is available in both languages.",
    w1h: "Fabricators & Countertop Shops",
    w1p: "Expand product mix, improve marketing, and attract higher-margin clients.",
    w2h: "Flooring & Surface Retailers",
    w2p: "Get found online, build referral systems, and position for premium clients.",
    w3h: "Remodelers & Contractors",
    w3p: "Build a marketing system that generates leads without depending on word of mouth alone.",
    w4h: "Spanish-Speaking Owners",
    w4p: "All services, tools, and communication available in Spanish. Hablamos su idioma.",
    "about-eyebrow": "Who I Am",
    "about-h2": "Hi, I'm David — 10 years living inside this industry.",
    "about-lead":
      "I started in sales and distribution for building products, working directly with fabricators, countertop shops, contractors, and designers. Over that decade I learned something most people in this space never talk about: the craft is rarely the problem. The business side is.",
    c1: "10 years in building products sales & distribution — surfaces, flooring, cabinets, vanities",
    c2: "Google & Meta Ads certified — ran paid campaigns and influencer collaborations",
    c3: "Helped business owners with websites, SEO, and growth strategy",
    c4: "Deep knowledge of the trade channel: fabricators, contractors, designers, builders",
    c5: "Bilingual — serves English and Spanish speaking shop owners across the US",
    c6: "Built and operated a marketing business from the ground up",
    "quote-text":
      '"I\'ve spent 10 years in this industry. I know how fabricators think, how contractors buy, and exactly where most shops are leaving money on the table."',
    "quote-attr": "— David, Surface Growth Advisor",
    "quote-body":
      "Shops lose revenue not because their work is bad — but because they're not marketing it, not capturing adjacent categories, not following up, and not positioned to attract the clients they actually want. I work with a small number of shops at a time so I can stay focused and deliver real results — not a cookie-cutter plan.",
    "bil-h2": "We speak your language",
    "bil-p":
      "A large part of the fabrication and surface industry is Spanish-speaking — and most consultants only serve English speakers. Everything I offer is available in both languages: audits, strategy calls, marketing materials, and more.",
    "bil-btn": "Take the Free Audit / Tome la Auditoría Gratuita →",
    "proc-eyebrow": "How It Works",
    "proc-h2": "Simple, focused, built around your schedule",
    pr1h: "Take the Free Growth Audit",
    pr1p: "13 yes/no questions across 5 areas of your business. Takes 5 minutes. You'll see exactly where you're leaving money on the table — before we ever talk.",
    pr2h: "Free 30-Minute Strategy Call",
    pr2p: "We review your audit results together. I share what I'm seeing and what I'd focus on first. No pitch, no pressure — just a real conversation about your business.",
    pr3h: "We Build a Plan Together",
    pr3p: "If it makes sense to work together, we choose the right plan for your budget and goals. Flexible payment options — start with a deposit and build from there.",
    pr4h: "Monthly Rhythm — Strategy to Results",
    pr4p: "Every month: identify the priority, execute on it, measure it, plan the next. No scattered effort — one focused area done well, every single month.",
    "acta-eyebrow": "Start Here — It's Free",
    "acta-h2": "Find out where your shop is leaving money on the table",
    "acta-p":
      "The growth audit takes 5 minutes and shows you exactly which areas of your business have untapped revenue. No sign-up required. Available in English and Spanish.",
    "acta-btn1": "Take the Free Audit →",
    "acta-btn2": "Auditoría en Español →",
    "con-eyebrow": "Get In Touch",
    "con-h2": "Ready to talk about your business?",
    "con-p": "Start with the free audit, or reach out directly. I respond within 24 hours — usually same day.",
    cd1b: "Response Time",
    cd1t: "Within 24 hours. Usually same day.",
    cd2b: "Free First Call",
    cd2t: "30 minutes, no obligation. We just talk about your business.",
    cd3b: "Bilingual",
    cd3t: "Available in English and Spanish. Hablamos español.",
    cd4b: "Location",
    cd4t: "Based in Utah — serving clients nationwide.",
    "f-name": "Your name",
    "f-biz": "Business name",
    "f-email": "Email address",
    "f-phone": "Phone number",
    "f-msg": "Tell me a little about your business...",
    "f-sel-placeholder": "What are you interested in?",
    "f-o1": "Free Growth Audit",
    "f-o2": "Free Strategy Call",
    "f-o3": "3-Month Plan ($5,000)",
    "f-o4": "12-Month Plan ($18,000)",
    "f-o5": "Just exploring",
    "f-btn": "Send My Message →",
    "f-note": "I respond within 24 hours. Usually same day.",
    "f-sent": "✓ Message Sent — I'll be in touch soon!",
    "footer-txt": "© 2025 Surface Growth Advisor LLC — Utah, USA. Serving clients nationwide.",
  },
  es: {
    "hero-eyebrow": "Consultoría de Negocios para Talleres y Superficies",
    "hero-h1": "Usted trabaja la piedra.<br/><em>Yo le ayudo a hacer<br/>crecer el negocio.</em>",
    "hero-sub":
      "Consultoría estratégica y mercadotecnia digital para fabricadores, talleres de encimeras y minoristas de superficies — de alguien que lleva 10 años en su industria.",
    "hero-btn1": "Tome la Auditoría Gratuita →",
    "hero-btn2": "Reserve una Llamada Gratuita",
    stat1: "Años en la Industria",
    stat2: "Idiomas",
    stat3: "Auditoría Gratis",
    stat4: "Llamada Gratis",
    "prob-eyebrow": "¿Le Suena Familiar?",
    "prob-h2": "La mayoría de los talleres son excelentes en el trabajo.<br/>El lado del negocio es otra historia.",
    p1h: "Clientes comprando en otro lugar",
    p1p: "Sus clientes de encimeras están comprando pisos, gabinetes y vanidades con un competidor — y usted ni siquiera está en la conversación.",
    p2h: "Invisible en línea",
    p2p: "Su trabajo es hermoso pero su sitio web está desactualizado, no aparece en Google y sus redes sociales son inconsistentes.",
    p3h: "Sin sistema de referidos",
    p3p: "Termina una excelente instalación y sigue adelante. Sin seguimiento, sin pedir referidos. Ingresos que deberían ser automáticos no lo son.",
    p4h: "Compitiendo por precio",
    p4p: "Sin posicionamiento premium, está atrapado compitiendo solo por precio — aunque su trabajo merece más.",
    "svc-eyebrow": "Lo Que Hago",
    "svc-h2": "Cuatro áreas donde marco la diferencia",
    "svc-lead": "Trabajo en estrategia y ejecución — para que no solo reciba ideas, sino que las cosas sucedan.",
    s1h: "Estrategia de Negocios",
    s1p: "Identificamos lo que está dejando sobre la mesa, priorizamos los movimientos de mayor impacto y construimos un plan de crecimiento de 90 días que puede ejecutar.",
    s1t1: "Auditoría de Crecimiento",
    s1t2: "Brechas de Ingresos",
    s1t3: "Mezcla de Productos",
    s2h: "Mercadotecnia Digital",
    s2p: "Anuncios en Google y Meta que traen clientes reales, SEO que lo hace encontrar localmente y un sitio web que convierte visitas en llamadas.",
    s3h: "Materiales de Mercadotecnia",
    s3p: "Folletos, listas de precios, campañas de correo, materiales para showroom — materiales profesionales que lo hacen ver como la opción premium.",
    s3t1: "Folletos",
    s3t2: "Campañas de Correo",
    s3t3: "Showroom",
    s4h: "Sistemas de Ventas",
    s4p: "Programas de referidos, secuencias de seguimiento y estrategias de relación con constructores y diseñadores que convierten instalaciones en cartera de clientes.",
    s4t1: "Referidos",
    s4t2: "Seguimiento",
    s4t3: "Constructores",
    "who-eyebrow": "A Quién Ayudo",
    "who-h2": "Hecho para el comercio — Inglés y Español",
    "who-lead":
      "Sirvo a propietarios de talleres en Utah y en todo el país. La mayoría de mis clientes hablan español — y todo lo que ofrezco está disponible en ambos idiomas.",
    w1h: "Fabricadores y Talleres de Encimeras",
    w1p: "Expandir la mezcla de productos, mejorar la mercadotecnia y atraer clientes de mayor margen.",
    w2h: "Minoristas de Pisos y Superficies",
    w2p: "Ser encontrado en línea, construir sistemas de referidos y posicionarse para clientes premium.",
    w3h: "Remodeladores y Contratistas",
    w3p: "Construir un sistema de mercadotecnia que genere clientes potenciales sin depender solo del boca a boca.",
    w4h: "Propietarios Hispanohablantes",
    w4p: "Todos los servicios, herramientas y comunicación disponibles en español. Hablamos su idioma.",
    "about-eyebrow": "Quién Soy",
    "about-h2": "Hola, soy David — 10 años viviendo dentro de esta industria.",
    "about-lead":
      "Comencé en ventas y distribución de productos de construcción, trabajando directamente con fabricadores, talleres de encimeras, contratistas y diseñadores. En esa década aprendí algo que la mayoría en este espacio nunca menciona: el trabajo rara vez es el problema. El lado del negocio sí lo es.",
    c1: "10 años en ventas y distribución de productos de construcción — superficies, pisos, gabinetes, vanidades",
    c2: "Certificado en Google y Meta Ads — administré campañas pagadas y colaboraciones con influencers",
    c3: "Ayudé a propietarios de negocios con sitios web, SEO y estrategia de crecimiento",
    c4: "Conocimiento profundo del canal comercial: fabricadores, contratistas, diseñadores, constructores",
    c5: "Bilingüe — sirve a propietarios de talleres en inglés y español en todo EE.UU.",
    c6: "Construí y opero un negocio de mercadotecnia desde cero",
    "quote-text":
      '"He pasado 10 años en esta industria. Sé cómo piensan los fabricadores, cómo compran los contratistas, y exactamente dónde la mayoría de los talleres están dejando dinero sobre la mesa."',
    "quote-attr": "— David, Surface Growth Advisor",
    "quote-body":
      "Los talleres pierden ingresos no porque su trabajo sea malo — sino porque no lo están mercadeando, no están capturando categorías adyacentes, no están haciendo seguimiento y no están posicionados para atraer a los clientes que realmente quieren. Trabajo con un número pequeño de talleres a la vez para mantenerme enfocado y entregar resultados reales — no un plan genérico.",
    "bil-h2": "Hablamos su idioma",
    "bil-p":
      "Una gran parte de la industria de fabricación y superficies es hispanohablante — y la mayoría de los consultores solo sirven a angloparlantes. Todo lo que ofrezco está disponible en ambos idiomas: auditorías, llamadas de estrategia, materiales de mercadotecnia y más.",
    "bil-btn": "Take the Free Audit / Tome la Auditoría Gratuita →",
    "proc-eyebrow": "Cómo Funciona",
    "proc-h2": "Simple, enfocado, construido alrededor de su horario",
    pr1h: "Tome la Auditoría Gratuita de Crecimiento",
    pr1p: "13 preguntas de sí o no en 5 áreas de su negocio. Toma 5 minutos. Verá exactamente dónde está dejando dinero sobre la mesa — antes de que hablemos.",
    pr2h: "Llamada de Estrategia Gratuita de 30 Minutos",
    pr2p: "Revisamos juntos los resultados de su auditoría. Comparto lo que estoy viendo y en qué me enfocaría primero. Sin presión — solo una conversación real sobre su negocio.",
    pr3h: "Construimos un Plan Juntos",
    pr3p: "Si tiene sentido trabajar juntos, elegimos el plan adecuado para su presupuesto y metas. Opciones de pago flexibles — empiece con un depósito y avance desde ahí.",
    pr4h: "Ritmo Mensual — Estrategia a Resultados",
    pr4p: "Cada mes: identificar la prioridad, ejecutarla, medirla, planear la siguiente. Sin esfuerzo disperso — un área enfocada bien hecha, cada mes.",
    "acta-eyebrow": "Empiece Aquí — Es Gratis",
    "acta-h2": "Descubra dónde está dejando dinero sobre la mesa",
    "acta-p":
      "La auditoría de crecimiento toma 5 minutos y le muestra exactamente qué áreas de su negocio tienen ingresos sin capturar. No requiere registro. Disponible en inglés y español.",
    "acta-btn1": "Take the Free Audit →",
    "acta-btn2": "Tome la Auditoría en Español →",
    "con-eyebrow": "Contáctenos",
    "con-h2": "¿Listo para hablar sobre su negocio?",
    "con-p": "Empiece con la auditoría gratuita, o contáctenos directamente. Respondo en 24 horas — generalmente el mismo día.",
    cd1b: "Tiempo de Respuesta",
    cd1t: "En 24 horas. Generalmente el mismo día.",
    cd2b: "Primera Llamada Gratis",
    cd2t: "30 minutos, sin compromiso. Solo hablamos de su negocio.",
    cd3b: "Bilingüe",
    cd3t: "Disponible en inglés y español. Hablamos español.",
    cd4b: "Ubicación",
    cd4t: "Basado en Utah — sirviendo clientes en todo el país.",
    "f-name": "Su nombre",
    "f-biz": "Nombre del negocio",
    "f-email": "Correo electrónico",
    "f-phone": "Número de teléfono",
    "f-msg": "Cuénteme un poco sobre su negocio...",
    "f-sel-placeholder": "¿En qué está interesado?",
    "f-o1": "Auditoría de Crecimiento Gratuita",
    "f-o2": "Llamada de Estrategia Gratuita",
    "f-o3": "Plan de 3 Meses ($5,000)",
    "f-o4": "Plan de 12 Meses ($18,000)",
    "f-o5": "Solo explorando",
    "f-btn": "Enviar Mi Mensaje →",
    "f-note": "Respondo en 24 horas. Generalmente el mismo día.",
    "f-sent": "✓ Mensaje Enviado — Le contactaré pronto!",
    "footer-txt": "© 2025 Surface Growth Advisor LLC — Utah, EE.UU. Sirviendo clientes en todo el país.",
  },
};
